### PR TITLE
symlink handling

### PR DESCRIPTION
**Pull request by phi-gamma**
Add options for handling symbolic links to guard against
malicious archives. By default, symlinks are handled as before.
When passing the option ``-8 «mode»``, a mode may be supplied:
with *all*, afio will ignore all symlinks; with *harmful* it will
ignore symlinks with potentially harmful targets. This includes
symlinks to both absolute locations and locations containing a
component that points to a parent directory (``..``).

This is a follow-up on a changeset I sent to @kholtman in private
earlier.

### CODE REVIEW

**Comment by kholtman** [comment]
I am nearly finished including these -- am doing this by hand based on earlier patch file.  Code diverged too much to allow for automatic merger.

**Comment by phi-gamma** [comment]
Just updated the patchset to fix a small issue in the test runner and to always emit a message when skipping symlinks, not just in verbose mode.

**Comment by kholtman** [comment]
I have used the test runner to create (in addition to my own tests) another test vector for the improved symlink handling code I wrote.  It passed on the vector.  I have decided against adapting the symlink.sh test script to make it a permanent part of the regression tests included with the afio release, because of a) adds little value to run these test always and b) existing regression test scripts have created several portability issues in the past, so I prefer to not add to them.

**Comment by kholtman** [comment]
Just uploaded last set of code changes for this issue (based partly on manually processing this pull request) to master branch.   This closes the pull request.

**Pull request closed without merging**
